# pg

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: connextoruser
  password: somepassword
  
development:
  <<: *default
  database: connextor_development
  
test:
  <<: *default
  database: connextor_test
